# Generated by Django 4.0.2 on 2022-02-14 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
