# Generated by Django 4.0.2 on 2022-02-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_category_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='category', verbose_name='Category Image'),
        ),
    ]
