# Generated by Django 4.0.2 on 2022-02-14 11:00

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_alter_category_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, help_text='Maximum file size allowed 900*900 or 2 MB', max_length=500, null=True, upload_to='category', validators=[app1.models.Category.validate_image], verbose_name='Category Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, help_text='Maximum file size allowed 900*900 or 2 MB', max_length=500, null=True, upload_to='product', validators=[app1.models.Product.validate_image], verbose_name='Product Image'),
        ),
    ]
