# Generated by Django 4.0.2 on 2022-02-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_alter_category_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='category', verbose_name='Category Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='product', verbose_name='Product Image'),
        ),
    ]
