# Generated by Django 4.0.2 on 2022-02-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_sales_sales_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sales_discount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Discount(%)'),
        ),
    ]
