# Generated by Django 4.0.2 on 2022-02-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_alter_sales_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Offer price'),
        ),
    ]
