# Generated by Django 4.0.2 on 2022-02-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
