# Generated by Django 4.0.2 on 2022-02-21 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0060_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
