# Generated by Django 4.0.2 on 2022-02-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0061_rename_images_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
    ]
