# Generated by Django 4.0.2 on 2022-02-22 04:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0064_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=ckeditor.fields.RichTextField(verbose_name='Short Description'),
        ),
    ]
