# Generated by Django 4.0.2 on 2022-02-22 06:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0070_remove_coupon_code_l'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='title',
        ),
        migrations.AddField(
            model_name='faq',
            name='Answer',
            field=ckeditor.fields.RichTextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='Question',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='Message',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
