# Generated by Django 4.0.2 on 2022-02-22 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0071_remove_faq_description_remove_faq_title_faq_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='Rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
