# Generated by Django 4.0.2 on 2022-02-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0073_rating_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Customer Address'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': ' Category'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name_plural': '  Products'},
        ),
        migrations.AlterField(
            model_name='rating',
            name='Status',
            field=models.CharField(choices=[('R', 'Reject'), ('A', 'Approved')], max_length=8),
        ),
    ]
