# Generated by Django 4.0.2 on 2022-02-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0077_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(blank=True, to='app1.image'),
        ),
    ]
