# Generated by Django 4.0.2 on 2022-02-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0078_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='Blog'),
        ),
    ]
