# Generated by Django 4.0.2 on 2022-02-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0083_remove_coupon_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name_plural': 'Sales/Discount'},
        ),
    ]
