# Generated by Django 4.0.2 on 2022-02-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0085_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
