# Generated by Django 4.0.2 on 2022-02-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0088_alter_contact_options_alter_faq_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
    ]
