# Generated by Django 4.0.2 on 2022-02-25 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0089_remove_coupon_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='custmer_message',
        ),
    ]
