# Generated by Django 4.0.2 on 2022-02-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0090_rename_contact_custmer_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='custmer_message',
            new_name='customer_message',
        ),
    ]
