# Generated by Django 4.0.2 on 2022-02-26 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0095_delete_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='Message',
            new_name='Reviews',
        ),
    ]
