# Generated by Django 4.0.2 on 2022-02-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0096_rename_message_rating_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='Status',
            field=models.CharField(choices=[('Reject', 'Reject'), ('Approve', 'Approved')], default=None, max_length=8),
        ),
    ]
