# Generated by Django 4.0.2 on 2022-03-29 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupons',
        ),
        migrations.CreateModel(
            name='redeemed_coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.cart')),
            ],
        ),
    ]
