# Generated by Django 4.0.2 on 2022-03-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_rating_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_message',
            name='Name',
        ),
        migrations.AddField(
            model_name='customer_message',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='customer_message',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Last Name'),
        ),
    ]
