# Generated by Django 4.0.2 on 2022-03-29 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_cart_coupons_redeemed_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemed_coupon',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.cart', verbose_name='coupon/user'),
        ),
    ]
