# Generated by Django 4.0.2 on 2022-06-13 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='Size',
        ),
    ]
