# Generated by Django 4.0.2 on 2022-03-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_faq_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtext',
            name='send_it',
        ),
        migrations.AddField(
            model_name='mailtext',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('s', 'sent')], default='d', max_length=1),
        ),
    ]
