# Generated by Django 4.0.2 on 2022-03-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_notification_created_date_notification_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification',
        ),
    ]
