# Generated by Django 4.0.2 on 2022-06-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_cart_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='p_idd',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
