# Generated by Django 4.0.2 on 2022-03-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
