# Generated by Django 4.0.2 on 2022-03-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_customer_message_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer_message',
            name='Phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer_message',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customer_message',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name'),
        ),
    ]
