# Generated by Django 4.0.2 on 2022-03-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_mailtext_send_it_mailtext_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtext',
            name='send_it',
            field=models.BooleanField(default=False),
        ),
    ]
