# Generated by Django 4.0.2 on 2022-03-29 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_redeemed_coupon_coupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer_message',
            options={'verbose_name_plural': 'Customer msgs/contact us'},
        ),
        migrations.AddField(
            model_name='redeemed_coupon',
            name='checkout_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.checkout', verbose_name='checkout product'),
        ),
        migrations.AlterField(
            model_name='redeemed_coupon',
            name='coupon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
