# Generated by Django 4.0.2 on 2022-03-29 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_customer_message_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='most_selled_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.product')),
            ],
            options={
                'verbose_name_plural': 'Most selled products',
            },
        ),
        migrations.CreateModel(
            name='latest_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.product')),
            ],
            options={
                'verbose_name_plural': 'Latest Products',
            },
        ),
    ]
