# Generated by Django 4.0.2 on 2022-03-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_mailtext_send_it'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtext',
            name='status',
        ),
    ]
