# Generated by Django 4.0.2 on 2022-03-01 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_address_city_alter_address_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='alternate_phone_no',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(11)], verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_no',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(11)], verbose_name='Phone'),
        ),
    ]
