# Generated by Django 4.0.2 on 2022-03-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_most_selled_products_latest_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(blank=True, max_length=255, null=True)),
                ('subscribed_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
            ],
        ),
    ]
