# Generated by Django 4.0.2 on 2022-03-18 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_brand_alter_product_category_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='title',
            new_name='brand_name',
        ),
    ]
