# Generated by Django 4.0.2 on 2022-03-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_product_rating_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating_average',
        ),
    ]
