# Generated by Django 4.0.2 on 2022-03-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_notification_alter_newsletter_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiryform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('Email', models.EmailField(max_length=50, null=True)),
                ('Phone', models.BigIntegerField(null=True)),
                ('Message', models.TextField(max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name_plural': 'FAQ Enquiry',
            },
        ),
    ]
