# Generated by Django 4.0.2 on 2022-03-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
