# Generated by Django 4.0.2 on 2022-03-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_enquiryform'),
    ]

    operations = [
        migrations.CreateModel(
            name='socialmedialinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(blank=True, max_length=100, null=True)),
                ('links', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Social media links',
            },
        ),
    ]
