# Generated by Django 4.0.2 on 2022-03-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_title_brand_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='last Name')),
                ('phone_number', models.BigIntegerField(null=True, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='Email')),
                ('address', models.TextField(null=True, verbose_name='Address')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(max_length=50, null=True, verbose_name='State')),
                ('postal_address', models.TextField(null=True, verbose_name='Postal address')),
            ],
        ),
    ]
