# Generated by Django 4.0.2 on 2022-03-31 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='checkout_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.checkout', verbose_name='Checked out product'),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
