# Generated by Django 4.0.2 on 2022-03-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_product_rating_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Coupon_code'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_discount',
            field=models.IntegerField(null=True, verbose_name='Discount(₹)'),
        ),
    ]
