# Generated by Django 4.0.2 on 2022-03-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_address_alternate_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='alternate_phone_no',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Alternate Phone'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_no',
            field=models.BigIntegerField(null=True, verbose_name='Phone'),
        ),
    ]
