# Generated by Django 4.0.2 on 2022-03-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_coupon_coupon_alter_coupon_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Pending', max_length=8, null=True),
        ),
    ]
