# Generated by Django 4.0.2 on 2022-03-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_cart_product_attributess_cartproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributess',
        ),
    ]
