# Generated by Django 4.0.2 on 2022-03-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_address_alternate_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_message',
            name='Email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer_message',
            name='Message',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer_message',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
