# Generated by Django 4.0.2 on 2022-03-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_notification_checkout_product_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='checkout_product',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
