# Generated by Django 4.0.2 on 2022-03-31 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_notification_checkout_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='notifications',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.notification'),
        ),
    ]
