# Generated by Django 4.0.2 on 2022-03-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='enddate',
            field=models.DateField(null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='startdate',
            field=models.DateField(null=True, verbose_name='Start Date'),
        ),
    ]
