# Generated by Django 4.0.2 on 2022-03-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_sales_sales_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='startdate',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_discount',
            field=models.IntegerField(null=True),
        ),
    ]
