# Generated by Django 4.0.2 on 2022-03-19 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
