# Generated by Django 4.0.2 on 2022-03-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_remove_orders_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
