# Generated by Django 4.0.2 on 2022-03-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_coupon_enddate_remove_coupon_startdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_active',
        ),
    ]
