# Generated by Django 4.0.2 on 2022-03-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_notification_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
