# Generated by Django 4.0.2 on 2022-03-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_remove_coupon_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ManyToManyField(blank=True, to='app1.image'),
        ),
    ]
