# Generated by Django 4.0.2 on 2022-03-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_remove_blog_image_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='images',
            field=models.ImageField(null=True, upload_to='blog'),
        ),
    ]
