# Generated by Django 4.0.2 on 2022-03-19 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_cart_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.address', verbose_name='Shpping Address')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.cart', verbose_name='Cart products')),
            ],
        ),
    ]
