# Generated by Django 4.0.2 on 2022-03-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_rename_order_id_notification_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sales',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
