# Generated by Django 4.0.2 on 2022-03-03 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_blog_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='brands',
        ),
    ]
