# Generated by Django 4.0.2 on 2022-02-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='category', verbose_name='Category Image', width_field=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='product', verbose_name='Product Image', width_field=300),
        ),
    ]
