# Generated by Django 4.0.2 on 2022-03-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_notification_product_notification_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='coupons',
            field=models.TextField(blank=True, null=True),
        ),
    ]
