# Generated by Django 4.0.2 on 2022-03-03 09:16

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_rename_title_category_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='brands',
            field=models.CharField(max_length=50, verbose_name='Brands'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='category', verbose_name='Brand Thumbnail'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.category', verbose_name='Product Brands'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='product', verbose_name='Product Thumbnail'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='Rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='Reviews',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
