# Generated by Django 4.0.2 on 2022-03-19 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_cart_attributes_remove_checkout_cart_checkout_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='Shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.address', verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='checkout_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.checkout', verbose_name='Checked out product'),
        ),
    ]
