# Generated by Django 4.0.2 on 2022-03-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_notification_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sales',
            field=models.TextField(blank=True, null=True),
        ),
    ]
