# Generated by Django 4.0.2 on 2022-03-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_checkout_shipping_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='ordered Date'),
        ),
    ]
