# Generated by Django 4.0.2 on 2022-03-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_orders_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtext',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('s', 'sent')], default='d', max_length=1),
        ),
    ]
