# Generated by Django 4.0.2 on 2022-04-04 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_notification_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sale',
        ),
    ]
