# Generated by Django 4.0.2 on 2022-04-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_remove_notification_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_account',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profile', verbose_name='Profle photo'),
        ),
    ]
