# Generated by Django 4.0.2 on 2022-03-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
