# Generated by Django 4.0.2 on 2022-04-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_my_account_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='alternate_phone_no',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='door_number',
        ),
        migrations.RemoveField(
            model_name='address',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
        migrations.RemoveField(
            model_name='my_account',
            name='postal_address',
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='address',
            name='fullname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='address',
            name='home',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Home'),
        ),
        migrations.AddField(
            model_name='address',
            name='locality',
            field=models.TextField(blank=True, null=True, verbose_name='locality'),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='address',
            name='work',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Work'),
        ),
        migrations.AddField(
            model_name='my_account',
            name='postal_pin',
            field=models.BigIntegerField(null=True, verbose_name='Postal address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Pin code'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
    ]
