# Generated by Django 4.0.2 on 2022-03-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_orders_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterModelOptions(
            name='checkout',
            options={'verbose_name_plural': 'Checkouts'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
