# Generated by Django 4.0.2 on 2022-04-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_remove_address_alternate_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='home',
            field=models.BooleanField(default=False, verbose_name='Home'),
        ),
        migrations.AlterField(
            model_name='address',
            name='work',
            field=models.BooleanField(default=False, verbose_name='Work'),
        ),
    ]
