# Generated by Django 4.0.2 on 2022-04-05 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_alter_address_home_alter_address_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.address', verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='links',
            field=models.URLField(blank=True, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='social_media',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='social media'),
        ),
    ]
