# Generated by Django 4.0.2 on 2022-02-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_category_is_active_product_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sales_discount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
