# Generated by Django 4.0.2 on 2022-03-04 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_mail_mailtext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mail',
        ),
        migrations.AlterField(
            model_name='mailtext',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
