# Generated by Django 4.0.2 on 2022-03-23 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_cart_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='coupons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.coupon'),
        ),
    ]
