# Generated by Django 4.0.2 on 2022-03-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_alter_cart_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='Coupon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
