# Generated by Django 4.0.2 on 2022-02-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_alter_sales_sales_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
    ]
