# Generated by Django 4.0.2 on 2022-03-04 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_alter_mailtext_message_alter_mailtext_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtext',
            name='users',
        ),
        migrations.AddField(
            model_name='mailtext',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
