# Generated by Django 4.0.2 on 2022-04-06 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_remove_category_brands_category_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='most_selled_products',
            name='orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.orders'),
        ),
    ]
