# Generated by Django 4.0.2 on 2022-03-04 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_remove_mailtext_users_mailtext_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtext',
            name='users',
        ),
        migrations.AddField(
            model_name='mailtext',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
