# Generated by Django 4.0.2 on 2022-02-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_sales_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active?'),
        ),
    ]
