# Generated by Django 4.0.2 on 2022-04-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_most_selled_products_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiryform',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Full Name'),
        ),
    ]
