# Generated by Django 4.0.2 on 2022-03-04 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_remove_mailtext_users_mailtext_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtext',
            name='attachment',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mailtext',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='mailtext',
            name='users',
        ),
        migrations.AddField(
            model_name='mailtext',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
