# Generated by Django 4.0.2 on 2022-03-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_alter_mailtext_attachment_alter_mailtext_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtext',
            name='attachment',
        ),
    ]
