# Generated by Django 4.0.2 on 2022-02-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_product_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.BigIntegerField(null=True, verbose_name='Offer price'),
        ),
    ]
