# Generated by Django 4.0.2 on 2022-05-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_user_is_used_alter_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(verbose_name='Short Description'),
        ),
    ]
