# Generated by Django 4.0.2 on 2022-05-20 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_alter_product_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='most_selled_products',
            name='orders',
        ),
    ]
