# Generated by Django 4.0.2 on 2022-05-20 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_alter_blog_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='images',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='url',
        ),
    ]
