# Generated by Django 4.0.2 on 2022-05-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_remove_blog_author_remove_blog_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
