# Generated by Django 4.0.2 on 2022-05-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_blog_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='linkdin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='twitter',
            field=models.URLField(null=True),
        ),
    ]
