# Generated by Django 4.0.2 on 2022-05-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_product_available_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.TextField(blank=True, null=True, verbose_name='Specification'),
        ),
    ]
