# Generated by Django 4.0.2 on 2022-05-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_faq_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ManyToManyField(blank=True, to='app1.Category')),
            ],
        ),
    ]
