# Generated by Django 4.0.2 on 2022-06-01 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': 'Notification'},
        ),
    ]
