# Generated by Django 4.0.2 on 2022-02-18 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
    ]
