# Generated by Django 4.0.2 on 2022-06-01 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_alter_notification_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_account',
            name='photo',
        ),
        migrations.CreateModel(
            name='userphoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='Profle photo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
