# Generated by Django 4.0.2 on 2022-02-18 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0050_product_product_image1_product_product_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.address', verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='attributes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.attributes', verbose_name=' Product Attributes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.category', verbose_name='Product Categoy'),
        ),
    ]
