# Generated by Django 4.0.2 on 2022-02-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0058_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='Product',
            new_name='product',
        ),
    ]
