# Generated by Django 4.0.2 on 2022-02-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0059_rename_product_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, to='app1.image'),
        ),
    ]
