# Generated by Django 4.0.2 on 2022-02-21 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0063_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.address', verbose_name='Shipping Address'),
        ),
    ]
