# Generated by Django 4.0.2 on 2022-02-22 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0069_banner_blog_contact_coupon_faq_alter_address_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='code_l',
        ),
    ]
