# Generated by Django 4.0.2 on 2022-02-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0076_coupon_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
