# Generated by Django 4.0.2 on 2022-02-23 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0080_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='attributes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.attributes', verbose_name=' Product Attributes'),
        ),
    ]
