# Generated by Django 4.0.2 on 2022-02-23 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0082_coupon_product_alter_image_image_alter_order_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='product',
        ),
    ]
