# Generated by Django 4.0.2 on 2022-02-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0086_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='Status',
            field=models.CharField(choices=[('Reject', 'Reject'), ('Approve', 'Approved')], max_length=8),
        ),
    ]
