# Generated by Django 4.0.2 on 2022-02-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0091_rename_custmer_message_customer_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
