# Generated by Django 4.0.2 on 2022-02-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0094_alter_blog_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
